# Generated by Django 4.2.7 on 2024-05-17 13:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_remove_blogpost_updated_on_blogpost_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
