# Generated by Django 4.2.7 on 2024-05-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_likedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='how_to_use',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='BlogPostTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
