# Generated by Django 4.2.7 on 2024-06-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0010_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
